### ISSUE TITLE
no code 

### ISSUE THREAD

**Issue by lxjlu** [tud-amr/go-mpc#2]
hi, i have not found any code for paper, is that open?

**Comment by bbrito** [comment]
Hi @lxjlu,

I still need to clean up the code and prepare it for release. I hope by mid of May to release the first version.

Best regards,
Bruno

**Comment by bbrito** [comment]
Yes. We will release soon a trained policy that you can test. The training algorithm is going to take a bit longer to cleanup.

**Comment by jonathanleinola** [comment]
Hey! Any progress/news on this project?

**Comment by weixians** [comment]
Hi, any plan to open to code? There is still no code until now.

**Comment by bbrito** [comment]
I am sorry for the delay. I am trying to finish my Ph.D. and plan to release the code after I deliver my thesis. Any day in January 2022.

**Comment by bbrito** [comment]
Dear all, the code has been released. I did not clean it properly yet but you can already test it. Please let me know if you find any issues.
